// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SC.SimpleMes.EntityFrameworkCore;

#nullable disable

namespace SC.SimpleMes.Migrations.ReportDb
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20240124074703_U_WorkProcessReport")]
    partial class U_WorkProcessReport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SC.SimpleMes.Report.DDWeekOnePassRateReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("BelongMonth")
                        .HasColumnType("int");

                    b.Property<int>("BelongWeek")
                        .HasColumnType("int");

                    b.Property<int>("BelongYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaterialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("NoramlPassCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NormalTestCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PassCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("RepairedPassDDCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RepairedTestCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTestCount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataDate");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("ProductLineId");

                    b.ToTable("DDWeekOnePassRateReports");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.OrgProductProcessWorkLoadReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinishedProductCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinishedRepairProductCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FirstFinishedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MaterialInfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaterialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProcessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ReceivedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StaticDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialInfoId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("WorkProcessId");

                    b.HasIndex("WorkStationId");

                    b.ToTable("OrgProductProcessWorkLoadReport");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.PrepaireWorkProcessDayReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BomUnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BomUniteCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CutMaterialUnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinishedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StaticDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("StaticDate");

                    b.HasIndex("WorkStationId");

                    b.ToTable("PrepaireWorkProcessDayReports");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.ProductLineCapacityDailyReportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinishedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InputCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StaticDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("StaticDate");

                    b.ToTable("ProductLineCapacityDailyReportRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.ProductLineOnePassRateReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExpectionCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinishedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("OnePassReate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StaticDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("StaticDate");

                    b.ToTable("ProductLineOnePassRateReports");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.View_DDTestDayKPI", b =>
                {
                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OperatorId"), 1L, 1);

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("OperatorId");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StaticDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TestAmounts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TestCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TestDDCount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OperatorId");

                    b.ToView("View_DDTestDayKPI");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.View_PrepareUserWorkStatic", b =>
                {
                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OperatorId"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("OperatorId");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MatrialCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OperatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrgId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProductlineId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WrapUniteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OperatorId");

                    b.ToView("View_PrepareUserWorkStatic");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.WorkProcessCapacityDailyReportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinishedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InputCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StaticDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("StaticDate");

                    b.HasIndex("WorkStationId");

                    b.ToTable("WorkProcessCapacityDailyReportRecord", (string)null);
                });

            modelBuilder.Entity("SC.SimpleMes.Report.WorkProcessOnePassRateReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExpectionCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinishedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("OnePassReate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StaticDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("StaticDate");

                    b.HasIndex("WorkStationId");

                    b.ToTable("WorkProcessOnePassRateReports");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.WorkProcessProblemDailyReportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("DataCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProbleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProblemDefineId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("QualityProblemNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StaticDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("ProblemDefineId");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("QualityProblemNumber");

                    b.HasIndex("StaticDate");

                    b.ToTable("WorkProcessProblemDailyReportRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
