<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>WLD.SimpleMes.Web.Mvc</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>WLD.SimpleMes.Web.Mvc</PackageId>
    <UserSecretsId>WLD-SimpleMes-56C2EF2F-ABD6-4EFC-AAF2-2E81C34E8FB1</UserSecretsId>
    <RootNamespace>WLD.SimpleMes.Web</RootNamespace>
    <TargetFramework>net5.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>

  <ItemGroup>
    <None Include="app.config" />
    <None Update="Dockerfile">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Update="wwwroot\**\*;Views\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WLD.SimpleMes.Web.Core\WLD.SimpleMes.Web.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Abp.Castle.NLog" Version="4.6.0.1" />
    <PackageReference Include="BuildBundlerMinifier" Version="3.2.447" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NLog" Version="4.7.10" />
    <PackageReference Include="PaulMiami.AspNetCore.Mvc.Recaptcha" Version="1.2.2" />
    <PackageReference Include="Abp.HangFire" Version="6.4.0" />
    <PackageReference Include="Abp.RedisCache" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\libs\" />
    <Folder Include="wwwroot\view-resources\Views\_Bundles\" />
  </ItemGroup>

</Project>

