// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SC.SimpleMes.EntityFrameworkCore;

#nullable disable

namespace SC.SimpleMes.Migrations.LogReportDb
{
    [DbContext(typeof(LogReportDbContext))]
    [Migration("20230419032450_Add_ProblemDailyReportTable")]
    partial class Add_ProblemDailyReportTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Abp.Authorization.Users.UserLoginAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BrowserInfo")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ClientIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Result")
                        .HasColumnType("tinyint");

                    b.Property<string>("TenancyName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserNameOrEmailAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AbpUserLoginAttempts");
                });

            modelBuilder.Entity("SC.SimpleMes.DynamicForms.FormInfoRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("BelongFormId")
                        .HasColumnType("bigint");

                    b.Property<string>("BelongMaterialBatchNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BelongOrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("BelongWorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("BelongWorkProcessNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FormRecordData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormUseType")
                        .HasColumnType("int");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Operator")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("OperatorTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("OperatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BelongFormId");

                    b.HasIndex("BelongMaterialBatchNumber");

                    b.HasIndex("BelongOrderNumber");

                    b.HasIndex("BelongWorkProcessNumber");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("OperatorTime");

                    b.HasIndex("OperatorUserId");

                    b.ToTable("FormInfoRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.JHTLog.NquartzJobLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BeginExcuteTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("ExcpetionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobResult")
                        .HasColumnType("int");

                    b.Property<string>("JobTypeFullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NquartzJobLogs");
                });

            modelBuilder.Entity("SC.SimpleMes.Log.JHTAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BrowserInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImpersonatorTenantId")
                        .HasColumnType("int");

                    b.Property<long?>("ImpersonatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("SC.SimpleMes.Material.BatchNumberPrintRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PrintCounts")
                        .HasColumnType("int");

                    b.Property<string>("PrintMachine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PrintTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PrintTime");

                    b.ToTable("BatchNumberPrintRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.Material.ERPInStockInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FSourceBillNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ReceiptQuantity")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("Specification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WarehousingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("WarehousingTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WhetherPrint")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BatchNo");

                    b.HasIndex("CreateTime");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("SourceType");

                    b.HasIndex("WarehousingNumber");

                    b.HasIndex("WarehousingTime");

                    b.ToTable("ERPInStockInfos");
                });

            modelBuilder.Entity("SC.SimpleMes.Material.MaterialBatchNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("BOMMaterialCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("BOMMaterialUnitName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("CreateProductLineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateWorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreateWorkStationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("FromErpBatchNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FromOrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsSerialsNumber")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPrintTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("MatrialCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrintTimes")
                        .HasColumnType("int");

                    b.Property<string>("Suppiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WrapUniteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("CreationTime");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.ToTable("MaterialBatchNumbers");
                });

            modelBuilder.Entity("SC.SimpleMes.QualityControl.ProblemDealRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DealTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperatorDescreption")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProblemDealType")
                        .HasColumnType("int");

                    b.Property<long>("ProblemRecordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DealTime");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProblemDealType");

                    b.HasIndex("ProblemRecordId");

                    b.ToTable("ProblemDealRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.QualityControl.ProblemRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchMaterilaNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("BelongProblemDefineId")
                        .HasColumnType("bigint");

                    b.Property<long>("BelongProductLineId")
                        .HasColumnType("bigint");

                    b.Property<long>("BelongWorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<long>("BelongWorkStaionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("DetailDescretion")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ExtensionData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEffect")
                        .HasColumnType("bit");

                    b.Property<string>("OnWorkProcessNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QualityProblemDefineNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WokrProcessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BatchMaterilaNumber");

                    b.HasIndex("CreationTime");

                    b.HasIndex("OnWorkProcessNumber");

                    b.HasIndex("QualityProblemDefineNumber");

                    b.HasIndex("WorkOrderNumber");

                    b.ToTable("ProblemRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.QualityControl.View_ProblemRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchMaterilaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Createor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DealTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailDescretion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProbleCategoryFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProbleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProblemDealType")
                        .HasColumnType("int");

                    b.Property<long?>("ProblemDefineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("View_ProblemRecord");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.ProductLineCapacityDailyReportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinishedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InputCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StaticDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("StaticDate");

                    b.ToTable("ProductLineCapacityDailyReportRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.WorkProcessCapacityDailyReportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinishedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InputCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StaticDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("StaticDate");

                    b.HasIndex("WorkStationId");

                    b.ToTable("WorkProcessCapacityDailyReportRecord", (string)null);
                });

            modelBuilder.Entity("SC.SimpleMes.Report.WorkProcessProblemDailyReportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProblemCount")
                        .HasColumnType("int");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StaticDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("StaticDate");

                    b.ToTable("WorkProcessProblemDailyReportRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.WorkProcess.WorkProcessMaterialRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal?>("BOMMaterialCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("BOMUnitName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputMaterialBatchNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("InputMaterialCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("InputMaterialName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InputMaterialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("InputMaterilId")
                        .HasColumnType("bigint");

                    b.Property<string>("InputUnitName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("OutRangeCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("ProductBatchNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WrokShopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InputMaterialBatchNumber");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("WorkProcessId");

                    b.HasIndex("WorkStationId");

                    b.ToTable("WorkProcessMaterialRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.WorkProcess.WorkProcessMaterialRecordHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal?>("BOMMaterialCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("BOMUnitName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputMaterialBatchNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("InputMaterialCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("InputMaterialName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InputMaterialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("InputMaterilId")
                        .HasColumnType("bigint");

                    b.Property<string>("InputUnitName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("OutRangeCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("ProductBatchNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WrokShopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InputMaterialBatchNumber");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("WorkProcessId");

                    b.HasIndex("WorkStationId");

                    b.ToTable("WorkProcessMaterialRecordHistory");
                });

            modelBuilder.Entity("SC.SimpleMes.WorkProcess.WorkProcessOperatorRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("CostTimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentOperatroAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNormalFinish")
                        .HasColumnType("bit");

                    b.Property<string>("OperatorDescreption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatroName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpertaorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WorkProcessNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkProcessOperateType")
                        .HasColumnType("int");

                    b.Property<long?>("WorkProcessSetId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("WrokShopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("CurrentOperatroAccountId");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("WorkProcessId");

                    b.HasIndex("WorkProcessOperateType");

                    b.HasIndex("WorkStationId");

                    b.ToTable("WorkProcessOperatorRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
