// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SC.SimpleMes.EntityFrameworkCore;

#nullable disable

namespace SC.SimpleMes.Migrations.LogReportDb
{
    [DbContext(typeof(LogReportDbContext))]
    [Migration("20231219081804_Add_OverUsedRecord")]
    partial class Add_OverUsedRecord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Abp.Authorization.Users.UserLoginAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BrowserInfo")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ClientIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Result")
                        .HasColumnType("tinyint");

                    b.Property<string>("TenancyName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserNameOrEmailAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AbpUserLoginAttempts");
                });

            modelBuilder.Entity("SC.SimpleMes.DynamicForms.DDImportantInfos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("AuditeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Auditor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("AuditorId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AvgChargeOCV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgChargeTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgDischargeOCV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgDischargeTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BelongMaterialBatchNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BelongOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BelongProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("BelongProductLineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ChargeAvgInternalResistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checkor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("CheckorId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CoulombEfficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentDensity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DischargeAvgInternalResistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DryWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectrolyteUtilization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyEfficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExtensionData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Humidity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InternalResistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InternalResistanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InternalResistanceBefore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAudited")
                        .HasColumnType("bit");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int>("LoopCount")
                        .HasColumnType("int");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatreialName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("NegativeAvgFlowRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NegativeCanAvgTempeature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OnInternalResistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OperatingPressure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OperatingTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PileThickness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PostiveAvgFlowRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PostiveCanAvgTempeature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PressThickness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProjectNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal>("Scores")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VoltageEfficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WetWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BelongMaterialBatchNumber");

                    b.HasIndex("BelongProductLineId");

                    b.HasIndex("MaterialNumber");

                    b.ToTable("DDImportantInfos");
                });

            modelBuilder.Entity("SC.SimpleMes.DynamicForms.FormInfoRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("BelongFormId")
                        .HasColumnType("bigint");

                    b.Property<string>("BelongMaterialBatchNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BelongOrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("BelongProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("BelongProductLineName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("BelongWorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("BelongWorkProcessNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FormRecordData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormUseType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatreialName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Operator")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("OperatorTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("OperatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BelongFormId");

                    b.HasIndex("BelongMaterialBatchNumber");

                    b.HasIndex("BelongOrderNumber");

                    b.HasIndex("BelongWorkProcessNumber");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("OperatorTime");

                    b.HasIndex("OperatorUserId");

                    b.ToTable("FormInfoRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.DynamicForms.View_DDImportantInfos", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("AuditeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Auditor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AuditorId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AvgChargeOCV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgChargeTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgDischargeOCV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgDischargeTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BelongMaterialBatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelongOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BelongProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("BelongProductLineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ChargeAvgInternalResistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checkor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CheckorId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CoulombEfficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentDensity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DischargeAvgInternalResistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DryWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectrolyteUtilization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyEfficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExtensionData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Humidity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InternalResistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InternalResistanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InternalResistanceBefore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAudited")
                        .HasColumnType("bit");

                    b.Property<int>("IsInStock")
                        .HasColumnType("int");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int>("LoopCount")
                        .HasColumnType("int");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatreialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NegativeAvgFlowRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NegativeCanAvgTempeature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OnInternalResistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OperatingPressure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OperatingTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PileThickness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PostiveAvgFlowRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PostiveCanAvgTempeature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PressThickness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Scores")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VoltageEfficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WetWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToView("View_DDImportantInfo");
                });

            modelBuilder.Entity("SC.SimpleMes.JHTLog.NquartzJobLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BeginExcuteTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("ExcpetionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobResult")
                        .HasColumnType("int");

                    b.Property<string>("JobTypeFullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NquartzJobLogs");
                });

            modelBuilder.Entity("SC.SimpleMes.LineSideWarehouse.LineSideMaterialOperatorRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("HandleUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("HandleUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LineSideMaterialInfoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OperatorCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OperatorStockTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OperatorTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("OperatorWorkShopId")
                        .HasColumnType("bigint");

                    b.Property<long>("OpertaorId")
                        .HasColumnType("bigint");

                    b.Property<string>("OpertaorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProjectNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StockOperatoerType")
                        .HasColumnType("int");

                    b.Property<string>("WorkOrderNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LineSideMaterialInfoId");

                    b.HasIndex("OperatorWorkShopId");

                    b.HasIndex("OpertaorId");

                    b.HasIndex("WorkOrderNumber");

                    b.ToTable("LineSideMaterialOperatorRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.LineSideWarehouse.View_LineSideMaterialOperatorRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("HandleUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LineSideMaterialInfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OperatorCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OperatorStockTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OperatorTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("OperatorWorkShopId")
                        .HasColumnType("bigint");

                    b.Property<long>("OpertaorId")
                        .HasColumnType("bigint");

                    b.Property<string>("OpertaorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockOperatoerType")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkShopName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("View_LineSideMaterialOperatorRecord");
                });

            modelBuilder.Entity("SC.SimpleMes.Log.JHTAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BrowserInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImpersonatorTenantId")
                        .HasColumnType("int");

                    b.Property<long?>("ImpersonatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("SC.SimpleMes.Material.BatchNumberPrintRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PrintCounts")
                        .HasColumnType("int");

                    b.Property<string>("PrintMachine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PrintTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PrintTime");

                    b.ToTable("BatchNumberPrintRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.Material.ERPInStockInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FSourceBillNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsedOut")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ReceiptQuantity")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("Specification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WarehousingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("WarehousingTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WhetherPrint")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BatchNo");

                    b.HasIndex("CreateTime");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("SourceType");

                    b.HasIndex("WarehousingNumber");

                    b.HasIndex("WarehousingTime");

                    b.ToTable("ERPInStockInfos");
                });

            modelBuilder.Entity("SC.SimpleMes.Material.MaterialBatchNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("BOMMaterialCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("BOMMaterialUnitName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("CreateProductLineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateWorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreateWorkStationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorIds")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("FlowNumber")
                        .HasColumnType("int");

                    b.Property<string>("FromErpBatchNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FromOrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSerialsNumber")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPrintTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("MatrialCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrintTimes")
                        .HasColumnType("int");

                    b.Property<string>("Suppiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WrapUniteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("CreationTime");

                    b.HasIndex("FlowNumber");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.ToTable("MaterialBatchNumbers");
                });

            modelBuilder.Entity("SC.SimpleMes.Material.View_MaterialBatchNumbers", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("BOMMaterialCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BOMMaterialUnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreateProductLineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateWorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreateWorkStationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("FlowNumber")
                        .HasColumnType("int");

                    b.Property<string>("FromErpBatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InputMaterialCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSerialsNumber")
                        .HasColumnType("bit");

                    b.Property<int>("IsUsed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastPrintTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MatrialCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrintTimes")
                        .HasColumnType("int");

                    b.Property<string>("Suppiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WrapUniteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("View_MaterialBatchNumbers");
                });

            modelBuilder.Entity("SC.SimpleMes.Material.View_OverUsedErpInstockInfo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("ActualUseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BatchNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FSourceBillNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstWarningTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsedOut")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastWarningTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReceiptQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehousingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WarehousingTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WhetherPrint")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToView("View_OverUsedErpInstockInfo");
                });

            modelBuilder.Entity("SC.SimpleMes.Material.WarningOverUsedERPInStockInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("ActualUseAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FirstWarningTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastWarningTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BatchNo");

                    b.HasIndex("FirstWarningTime");

                    b.ToTable("WarningOverUsedERPInStockInfos");
                });

            modelBuilder.Entity("SC.SimpleMes.QualityControl.ProblemDealRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DealTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperatorDescreption")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProblemDealType")
                        .HasColumnType("int");

                    b.Property<long>("ProblemRecordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DealTime");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProblemDealType");

                    b.HasIndex("ProblemRecordId");

                    b.ToTable("ProblemDealRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.QualityControl.ProblemRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchMaterilaNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("BelongProblemDefineId")
                        .HasColumnType("bigint");

                    b.Property<long>("BelongProductLineId")
                        .HasColumnType("bigint");

                    b.Property<long>("BelongWorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<long>("BelongWorkStaionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("DetailDescretion")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ExtensionData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEffect")
                        .HasColumnType("bit");

                    b.Property<string>("OnWorkProcessNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QualityProblemDefineNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ResponsibleWorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WokrProcessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BatchMaterilaNumber");

                    b.HasIndex("CreationTime");

                    b.HasIndex("OnWorkProcessNumber");

                    b.HasIndex("QualityProblemDefineNumber");

                    b.HasIndex("WorkOrderNumber");

                    b.ToTable("ProblemRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.QualityControl.View_ProblemRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchMaterilaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Createor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DealTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailDescretion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProbleCategoryFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProbleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProblemDealType")
                        .HasColumnType("int");

                    b.Property<long?>("ProblemDefineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("View_ProblemRecord");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.View_BatchMaterialUsedReport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BatchNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DDUsedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IsOverUsed")
                        .HasColumnType("int");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrepaireMaterialCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReceiptQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("View_BatchMaterialUsedReport");
                });

            modelBuilder.Entity("SC.SimpleMes.Report.View_ProductConstructMaterialInfo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CurrentProductLineId")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentWorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentWorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("InputMaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputMaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialBatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProduceStatus")
                        .HasColumnType("int");

                    b.Property<string>("ProductLineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("View_ProductConstructMaterialInfo");
                });

            modelBuilder.Entity("SC.SimpleMes.WorkOrder.View_OverUseWorkOrderInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ActrualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActuralEndTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("BOMId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinishedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FirstWarningTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastWarningTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("MaterialInfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlanEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlanStartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProdcuingCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProduceCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ProduceLineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProduceWorkShopId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductLineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<long?>("WorkOrderBomId")
                        .HasColumnType("bigint");

                    b.Property<int>("WorkOrderStatu")
                        .HasColumnType("int");

                    b.Property<long?>("WorkProcessSetId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkShopName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkShopNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("View_OverUseWorkOrderInfo");
                });

            modelBuilder.Entity("SC.SimpleMes.WorkOrder.WarningOverUsedWorkOrderRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("FirstWarningTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastWarningTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FirstWarningTime");

                    b.HasIndex("WorkOrderNumber");

                    b.ToTable("WarningOverUsedWorkOrderRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.WorkProcess.WorkProcessMaterialRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal?>("BOMMaterialCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("BOMUnitName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BatchNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputMaterialBatchNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("InputMaterialCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("InputMaterialName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InputMaterialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("InputMaterilId")
                        .HasColumnType("bigint");

                    b.Property<string>("InputUnitName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("OutRangeCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("ProductBatchNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("Supplier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("WarehousingTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WrokShopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InputMaterialBatchNumber");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("WorkProcessId");

                    b.HasIndex("WorkStationId");

                    b.ToTable("WorkProcessMaterialRecords");
                });

            modelBuilder.Entity("SC.SimpleMes.WorkProcess.WorkProcessMaterialRecordHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal?>("BOMMaterialCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("BOMUnitName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BatchNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputMaterialBatchNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("InputMaterialCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("InputMaterialName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InputMaterialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("InputMaterilId")
                        .HasColumnType("bigint");

                    b.Property<string>("InputUnitName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("OutRangeCount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("ProductBatchNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("Supplier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("WarehousingTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WrokShopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InputMaterialBatchNumber");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("WorkProcessId");

                    b.HasIndex("WorkStationId");

                    b.ToTable("WorkProcessMaterialRecordHistory");
                });

            modelBuilder.Entity("SC.SimpleMes.WorkProcess.WorkProcessOperatorRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("CostTimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentOperatroAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNormalFinish")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRepaired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OperatorDescreption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatroName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpertaorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductLineId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkProcessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WorkProcessNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkProcessOperateType")
                        .HasColumnType("int");

                    b.Property<long?>("WorkProcessSetId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkStationName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("WrokShopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("CurrentOperatroAccountId");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("WorkProcessId");

                    b.HasIndex("WorkProcessOperateType");

                    b.HasIndex("WorkStationId");

                    b.ToTable("WorkProcessOperatorRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
